### ISSUE TITLE
Unable to install plugin on IOS

### ISSUE THREAD

**Issue by viveknarula1980** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#179]
Hi,

I am unable to install plugin on MAC, even on a fresh build black ionic repository. I have used this plugin in many of my previous projects however this time, its not working. 

Error -
`Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
Failed to install 'cordova-plugin-fcm-with-dependecy-updated': undefined
CordovaError: Promise rejected with non-error: '/bin/sh: /usr/local/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory\n'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova plugin add cordova-plugin-fcm-with-dependecy-updated --save 
        exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more 
        information.
`
Environment -

```
Ionic:

   ionic (Ionic CLI)             : 4.11.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : ios 5.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 5 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.3 Build version 11C29
```
 Please let me know if any other information is required. 

Thanks,
Vivek

**Comment by andrehtissot** [comment]
Hi @viveknarula1980,

Please share the output of `ruby --version` and `pod --version`

**Comment by PoeticArcher** [comment]
I'm having this same issue. I have an automated deployment for our apps and it broke after you added the IOS_FIREBASE_MESSAGING_VERSION variable. Something isn't getting set automatically in ios for those of us with existing config.xml and package.jsons. The error is ArgumentError - Illformed requirement `"$IOS_FIREBASE_MESSAGING_VERSION"` after 	pod 'Firebase/Messaging', '$IOS_FIREBASE_MESSAGING_VERSION'

RUBY: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
RUBY GEMS: 3.0.3
Xcode: 12.1
POD: 1.9.3

**Comment by Florian-crg** [comment]
I have trouble installing fcm for iOS as well.  

On Android it works like a charm. It seems that it has a pod problem. 

`pod --version 1.10.1`
`ruby --version  ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]`


```
Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-fcm-with-dependecy-updated': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/ecovelo/Projects/appli-usager-v2/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (node:events:379:20)
    at maybeClose (node:internal/child_process:1069:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:300:5)
pod: Command failed with exit code 1
[ERROR] An error occurred while running subprocess cordova. 

```
