### ISSUE TITLE
Can't install latest version in Windows

### ISSUE THREAD

**Issue by Herna1994** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#208]
Installing "cordova-plugin-fcm-with-dependecy-updated" for android
Subproject Path: CordovaLib
Subproject Path: app
Running hook: C:\Users\herna\Desktop\Desarrollo\delegacionDeportes\plugins\cordova-plugin-fcm-with-dependecy-updated\scripts\install_ionic_dependencies.bat C:\Users\herna\Desktop\Desarrollo\delegacionDeportes
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install', '--loglevel', 'error', '--no-progress' ]
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install', '--loglevel', 'error', '--no-progress' ]
}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install', '--loglevel', 'error', '--no-progress' ]
}
Failed to install 'cordova-plugin-fcm-with-dependecy-updated': Error: Command failed with exit code 1: C:\Users\herna\Desktop\Desarrollo\delegacionDeportes\plugins\cordova-plugin-fcm-with-dependecy-updated\scripts\install_ionic_dependencies.bat C:\Users\herna\Desktop\Desarrollo\delegacionDeportes
    at makeError (C:\Users\herna\AppData\Roaming\npm\node_modules\cordova\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\herna\AppData\Roaming\npm\node_modules\cordova\node_modules\execa\index.js:114:26)
Command failed with exit code 1: C:\Users\herna\Desktop\Desarrollo\delegacionDeportes\plugins\cordova-plugin-fcm-with-dependecy-updated\scripts\install_ionic_dependencies.bat C:\Users\herna\Desktop\Desarrollo\delegacionDeportes
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd plugin add cordova-plugin-fcm-with-dependecy-updated exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**Comment by andrehtissot** [comment]
Please upgrade to version 7.6.1,

Let me know if the issue persists.

**Comment by Herna1994** [comment]
It does seem to work, but I get this which is really weird.

Adding cordova-plugin-fcm-with-dependecy-updated to package.json
Android-specific google-services.json file not found!

**Comment by Herna1994** [comment]
Nevermind, it was just a warning, but it compiles so far :)
