### ISSUE TITLE
plugin add cordova-plugin-fcm-with-dependecy-updated errors

### ISSUE THREAD

**Issue by namikarif** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#256]
I can't add the FCM plugin. Plugin add time gives the following error:

`Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
Running command: pod install --verbose
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1

Failed to install 'cordova-plugin-fcm-with-dependecy-updated': Error: pod: Command failed with exit code 1 Error output:
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
    at ChildProcess.whenDone (/Users/namik/Desktop/Namiq/CargoDiem/Mobile/CargoDiem Mobil/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
pod: Command failed with exit code 1 Error output:
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
[ERROR] An error occurred while running subprocess cordova.
        
        cordova plugin add cordova-plugin-fcm-with-dependecy-updated exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
`

**Comment by kputh** [comment]
Have you tried following the instructions and doing something like

```sh
cd platforms/io
gem pristine ffi --version 1.13.1
```

I think I had to run `sudo gem pristine ffi --version 1.13.1` instead of the second line to make it work.
