### ISSUE TITLE
IOS  - lugin add cordova-plugin-fcm-with-dependecy-updated not working

### ISSUE THREAD

**Issue by dineshmaths1** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#260]
ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated
> cordova plugin add cordova-plugin-fcm-with-dependecy-updated
Installing "cordova-plugin-fcm-with-dependecy-updated" for ios

after that nothing happening on the screen
still waiting to complete the process

**Comment by dineshmaths1** [comment]
Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-fcm-with-dependecy-updated': CordovaError: Uh oh!
"/Users/hanumantb/Documents/titheeworking/platforms/ios/MyApp/Plugins/cordova-plugin-fcm-with-dependecy-updated/FCMPlugin.m" already exists!
    at copyNewFile (/Users/hanumantb/Documents/titheeworking/platforms/ios/cordova/lib/plugman/pluginHandlers.js:333:45)
    at installHelper (/Users/hanumantb/Documents/titheeworking/platforms/ios/cordova/lib/plugman/pluginHandlers.js:259:13)
    at install (/Users/hanumantb/Documents/titheeworking/platforms/ios/cordova/lib/plugman/pluginHandlers.js:34:13)
    at ActionStack.process (/Users/hanumantb/Documents/titheeworking/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/hanumantb/Documents/titheeworking/node_modules/cordova-common/src/PluginManager.js:112:24)
    at PluginManager.addPlugin (/Users/hanumantb/Documents/titheeworking/node_modules/cordova-common/src/PluginManager.js:142:21)
    at Api.addPlugin (/Users/hanumantb/Documents/titheeworking/platforms/ios/cordova/Api.js:254:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:561:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:344:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Uh oh!
"/Users/hanumantb/Documents/titheeworking/platforms/ios/MyApp/Plugins/cordova-plugin-fcm-with-dependecy-updated/FCMPlugin.m" already exists!
[ERROR] An error occurred while running subprocess cordova.
        
        cordova plugin add cordova-plugin-fcm-with-dependecy-updated exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.

**Comment by ahmadalmunajjed** [comment]
Did you manage to fix it?
