### ISSUE TITLE
IOS -  cordova platform add ios error

### ISSUE THREAD

**Issue by dineshmaths1** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#261]
cordova platform rm  ios &&  cordova platform add ios
Using cordova-fetch for cordova-ios@^6.1.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.tithee.com
	Name: MyApp
iOS project created with cordova-ios@6.2.0
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-fcm-with-dependecy-updated': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/hanumantb/Documents/titheeworking/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:376:20)
    at Pipe.<anonymous> (net.js:673:12)
pod: Command failed with exit code 1

**Comment by sarathi0333** [comment]
As suggested in the error message can you run `pod install --verbose` after this in `platforms/ios` and post the error message, if you get any.

**Comment by ahmadalmunajjed** [comment]
Did you manage to fix it?
