### ISSUE TITLE
Push Notification Not Working On iOS with cordova-plugin-fcm-with-dependency-updated .

### ISSUE THREAD

**Issue by vivekkumarbiswal** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#309]
Hello @andrehtissot & all i am facing problem with push notification with iOS application but its completely working fine with android (i have build an ionic cordova hybrid application).
I think the push notification was working fine before i updating iOS 16.1 SDK (xcode 14.3).

Issues i m facing while building: (ionic cordova build ios --configuration production --release)

<img width="1109" alt="Screenshot 2023-08-28 at 15 14 27" src="https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/assets/67514800/f0f87f25-c494-4585-84f9-ac90b9083f09">

but when i do edit the pod file with a specific version ~> 7.4.0 (Firebase/Messaging version) and do pod install  and then build it again then it got build successfully without any error and all functionality is working perfectly in the application but the **push notification is not working**.

**Note:** if i m putting any other versions except 7.4.0 the pod install is getting succeeded but the build is getting failed.

**Pod File:**

<img width="769" alt="Screenshot 2023-08-28 at 15 12 03" src="https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/assets/67514800/aecac173-a713-432a-bac1-6a144f83ab81">

**to**

<img width="716" alt="Screenshot 2023-08-28 at 16 48 20" src="https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/assets/67514800/a078a733-be30-4530-b07e-f0455e8e02bb">

**pod install:**

<img width="569" alt="Screenshot 2023-08-28 at 17 12 49" src="https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/assets/67514800/60f3ec1a-ef52-4aff-b724-dae0e6e24bc6">

**node version:**
v14.17.3

**npm version**
6.14.13

**cordova version**
11.1.0

**ionic version**
5.4.16

**Pod version(cocoapods)**
1.11.2

System:
macOS Ventura (13.2.1)
Xcode 14.3

Thank you!

**Comment by carlo318** [comment]
I am also working on a Ionic (hybrid) APP and this plugin is working fine on Android.
On IOS it is compiled successfully, but the notifications no more arrive on  Apple devices. 
It was working fine until mid August 2023. Is it anything changed on Firebase side?

**Comment by vivekkumarbiswal** [comment]
Hello @carlo318 its the same case with me also. I tired finding on firebase side but didn't get anything there.Please let me know if you get any solution to this issue, It will be a great help.

Thank you !

**Comment by carlo318** [comment]
Hi @vivekkumarbiswal finally I solved with these 2 actions:
1) reinstalling the plugin with ALL the parameters suggested in the ReadMe:

`ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated   --variable ANDROID_DEFAULT_NOTIFICATION_ICON="@mipmap/ic_launcher"   --variable ANDROID_FIREBASE_BOM_VERSION="26.0.0" 
  --variable ANDROID_GOOGLE_SERVICES_VERSION="4.3.4"   --variable ANDROID_GRADLE_TOOLS_VERSION="4.1.0" 
  --variable IOS_FIREBASE_MESSAGING_VERSION="~> 7.4.0"`

2) Inserting the explicit request for the Permission to receive the Push Notifications:

`const wasPermissionGiven = await FCM.requestPushPermission({  });`

If still not working, try removing the platform IOS, remove the plugin, reinstall the plugin, then reinstall the platform IOS.

**Comment by vivekkumarbiswal** [comment]
> Hi @vivekkumarbiswal finally I solved with these 2 actions:
> 
> 1. reinstalling the plugin with ALL the parameters suggested in the ReadMe:
> 
> `ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated --variable ANDROID_DEFAULT_NOTIFICATION_ICON="@mipmap/ic_launcher" --variable ANDROID_FIREBASE_BOM_VERSION="26.0.0" --variable ANDROID_GOOGLE_SERVICES_VERSION="4.3.4" --variable ANDROID_GRADLE_TOOLS_VERSION="4.1.0" --variable IOS_FIREBASE_MESSAGING_VERSION="~> 7.4.0"`
> 
> 2. Inserting the explicit request for the Permission to receive the Push Notifications:
> 
> `const wasPermissionGiven = await FCM.requestPushPermission({ });`
> 
> If still not working, try removing the platform IOS, remove the plugin, reinstall the plugin, then reinstall the platform IOS.

Hello @carlo318 i tried reinstalling the plugin its failing and i tried removing platform(ios) and plugin, i m able to install the plugin but while adding platform its giving the same error :

Installing "cordova-plugin-fcm-with-dependecy-updated" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-fcm-with-dependecy-updated': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/vivekbiswal/Documents/IOS/Push Notification/website/FSPortal/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
pod: Command failed with exit code 1
[ERROR] An error occurred while running subprocess cordova.
cordova platform add ios exited with exit code 1.
Re-running this command with the --verbose flag may provide more information. 

do you know how to resolve this ?

**Comment by carlo318** [comment]
I am sorry I don't know how to help you, I don't get that error.

**Comment by vivekkumarbiswal** [comment]
It got resolved as the issue is not with the plugin its because my app was not using the FCM request push permission, after putting the FCM request push permission its working now.

**Comment by kunalSBasic** [comment]
> It got resolved as the issue is not with the plugin its because my app was not using the FCM request push permission, after putting the FCM request push permission its working now.

Is it working on the Android 13 & the latest iOS? Are you able to receive the Push notification successfully?
